/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ezbookingdisprogclient;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ivanc
 */
public class FormPartnerRestaurant extends javax.swing.JFrame {

    byte[] receivedData, sendData;
    DatagramSocket clientSocket;
    DatagramPacket receivedPacket, sendPacket;

    /**
     * Creates new form FormPartnerRestaurant
     */
    public FormPartnerRestaurant() {
        try {
            clientSocket = new DatagramSocket(1000);
            initComponents();
        } catch (SocketException ex) {
            Logger.getLogger(FormPartnerRestaurant.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNamaPemilik = new javax.swing.JTextField();
        jNumberPlate = new javax.swing.JLabel();
        jNumberPlate1 = new javax.swing.JLabel();
        txtNamaRestaurant = new javax.swing.JTextField();
        jNumberPlate2 = new javax.swing.JLabel();
        jNumberPlate3 = new javax.swing.JLabel();
        txtJumlahTable = new javax.swing.JTextField();
        txtUsernameRestaurant = new javax.swing.JTextField();
        BtnInput = new javax.swing.JButton();
        jNumberPlate4 = new javax.swing.JLabel();
        txtAlamatRestaurant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EZBOOKING RESTAURANT PARTNER");

        jNumberPlate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNumberPlate.setText("Nama Pemilik : ");

        jNumberPlate1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNumberPlate1.setText("Nama Restaurant : ");

        jNumberPlate2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNumberPlate2.setText("Username Restaurant : ");

        jNumberPlate3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNumberPlate3.setText("Jumlah Table : ");

        BtnInput.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnInput.setText("INPUT");
        BtnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInputActionPerformed(evt);
            }
        });

        jNumberPlate4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNumberPlate4.setText("Alamat Restaurant : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNumberPlate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNamaPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNumberPlate2)
                            .addComponent(jNumberPlate3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsernameRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlahTable, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNumberPlate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNamaRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jNumberPlate4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAlamatRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumberPlate)
                    .addComponent(txtNamaPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumberPlate1)
                    .addComponent(txtNamaRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumberPlate4)
                    .addComponent(txtAlamatRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNumberPlate2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jNumberPlate3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUsernameRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJumlahTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(BtnInput)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInputActionPerformed
        try {
            receivedData = new byte[2048];
            sendData = new byte[2048];

            InetAddress ipServer = InetAddress.getByName("localhost");
            int portServer = 2000;

            String namaPemilik = txtNamaPemilik.getText();
            String namaRestaurant = txtNamaRestaurant.getText();
            String alamatRestaurant = txtAlamatRestaurant.getText();
            String usernameRestaurant = txtUsernameRestaurant.getText();
            int jumlahTable = Integer.parseInt(txtJumlahTable.getText());

            String send = "ADDRESTAURANT/" + namaPemilik + "/" + namaRestaurant + "/" + usernameRestaurant + "/" + alamatRestaurant + "/" + jumlahTable;
            sendData = send.getBytes();

            sendPacket = new DatagramPacket(sendData, sendData.length, ipServer, portServer);
            clientSocket.send(sendPacket);

            receivedPacket = new DatagramPacket(receivedData, receivedData.length);
            clientSocket.receive(receivedPacket);

            String received = new String(receivedPacket.getData(), receivedPacket.getOffset(), receivedPacket.getLength());
            JOptionPane.showMessageDialog(this, received, "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

            txtNamaPemilik.setText("");
            txtNamaRestaurant.setText("");
            txtAlamatRestaurant.setText("");
            txtUsernameRestaurant.setText("");
            txtJumlahTable.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error : " + e.getMessage());
        }

    }//GEN-LAST:event_BtnInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPartnerRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPartnerRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPartnerRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPartnerRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPartnerRestaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNumberPlate;
    private javax.swing.JLabel jNumberPlate1;
    private javax.swing.JLabel jNumberPlate2;
    private javax.swing.JLabel jNumberPlate3;
    private javax.swing.JLabel jNumberPlate4;
    private javax.swing.JTextField txtAlamatRestaurant;
    private javax.swing.JTextField txtJumlahTable;
    private javax.swing.JTextField txtNamaPemilik;
    private javax.swing.JTextField txtNamaRestaurant;
    private javax.swing.JTextField txtUsernameRestaurant;
    // End of variables declaration//GEN-END:variables
}
