/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FormRestaurant;

import FormRegistrasiAccount.FormLogIn;
import com.ubaya.disprog.Report;
import com.ubaya.disprog.Reservasi;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author asus
 */
public class FormShowReservasi extends javax.swing.JFrame {

    com.ubaya.disprog.EzBookingWebService_Service service;
    com.ubaya.disprog.EzBookingWebService port;

//    private static JButton btnAccept = new JButton();
//    private static JButton btnDecline = new JButton();
//    private static JButton btnArrived = new JButton();
    Reservasi reservasi = new Reservasi();
    List<Reservasi> res = new ArrayList<>();

    /**
     * Creates new form form
     */
    public FormShowReservasi() {
        initComponents();
        service = new com.ubaya.disprog.EzBookingWebService_Service();
        port = service.getEzBookingWebServicePort();
        String usernameRestaurant = FormLogIn.txtUsername.getText();
        int idResto = idRestaurant(usernameRestaurant);
        res = port.showReservasi(idResto);

        DefaultTableModel model = (DefaultTableModel) tableReservation.getModel();
        for (int i = 0; i < res.size(); i++) {
            reservasi = res.get(i);
            model.addRow(new Object[]{reservasi.getId(), reservasi.getAccountUsername(), reservasi.getTanggalPesanan(), reservasi.getJumlahMeja(), reservasi.getJumlahOrang()});
        }
    }

    public int idRestaurant(String username) {
        service = new com.ubaya.disprog.EzBookingWebService_Service();
        port = service.getEzBookingWebServicePort();
        return port.getIdRestaurant(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReview = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReservation = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAcpt = new javax.swing.JButton();
        btnDec = new javax.swing.JButton();
        btnArrived = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReview.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        lblReview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReview.setText("TABLE RESERVATION");
        lblReview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESTAURANT RESERVATION");

        tableReservation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 195, 0)));
        tableReservation.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        tableReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation Id", "Reservant Name", "Reservation Date", "Total Table", "Number of People"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReservationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableReservation);
        if (tableReservation.getColumnModel().getColumnCount() > 0) {
            tableReservation.getColumnModel().getColumn(0).setResizable(false);
            tableReservation.getColumnModel().getColumn(1).setResizable(false);
            tableReservation.getColumnModel().getColumn(2).setResizable(false);
            tableReservation.getColumnModel().getColumn(3).setResizable(false);
            tableReservation.getColumnModel().getColumn(4).setResizable(false);
        }

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAcpt.setText("Accept");
        btnAcpt.setEnabled(false);
        btnAcpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcptActionPerformed(evt);
            }
        });

        btnDec.setText("Decline");
        btnDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecActionPerformed(evt);
            }
        });

        btnArrived.setText("Arrived");
        btnArrived.setEnabled(false);
        btnArrived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrivedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lblReview, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnArrived)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAcpt)
                        .addGap(18, 18, 18)
                        .addComponent(btnDec)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(4, 4, 4)
                .addComponent(lblReview, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAcpt)
                        .addComponent(btnArrived))
                    .addComponent(btnDec))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        FormHomeRestaurant frm = new FormHomeRestaurant();
        frm.setEnabled(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAcptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcptActionPerformed
        service = new com.ubaya.disprog.EzBookingWebService_Service();
        port = service.getEzBookingWebServicePort();

        int row = tableReservation.getSelectedRow();
        int idReservation = (int) tableReservation.getValueAt(row, 0);

        boolean res = true;
        res = port.updateStatusReservasi("Confirmed", idReservation);
        JOptionPane.showMessageDialog(null, "Success Confirm this reservation");
        btnAcpt.setEnabled(false);
        btnArrived.setEnabled(true);
    }//GEN-LAST:event_btnAcptActionPerformed

    private void tableReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReservationMouseClicked
        service = new com.ubaya.disprog.EzBookingWebService_Service();
        port = service.getEzBookingWebServicePort();
        String usernameRestaurant = FormLogIn.txtUsername.getText();
        int row = tableReservation.getSelectedRow();
        int idReservasi = (int) tableReservation.getValueAt(row, 0);
        String hasil;
        hasil = port.getStatusReservasi(idReservasi);
        if (hasil.equals("On Process")) {
            btnAcpt.setEnabled(true);
            btnArrived.setEnabled(false);
            btnDec.setEnabled(true);
        } else if (hasil.equals("Confirmed")) {
            btnAcpt.setEnabled(false);
            btnArrived.setEnabled(true);
            btnDec.setEnabled(true);
        } else {
            btnAcpt.setEnabled(false);
            btnArrived.setEnabled(false);
            btnDec.setEnabled(false);
        }
    }//GEN-LAST:event_tableReservationMouseClicked

    private void btnArrivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrivedActionPerformed
        service = new com.ubaya.disprog.EzBookingWebService_Service();
        port = service.getEzBookingWebServicePort();

        int row = tableReservation.getSelectedRow();
        int idReservation = (int) tableReservation.getValueAt(row, 0);

        boolean result = true;
        result = port.updateStatusReservasi("Arrived", idReservation);
        JOptionPane.showMessageDialog(null, "The Customer already Arrived");
        btnArrived.setEnabled(false);
        btnDec.setEnabled(false);

        String usernameRestaurant = FormLogIn.txtUsername.getText();
        int idResto = idRestaurant(usernameRestaurant);
        res = new ArrayList<>();
        res = port.showReservasi(idResto);
        DefaultTableModel model = (DefaultTableModel) tableReservation.getModel();
        model.setRowCount(0);
        for (int i = 0; i < res.size(); i++) {
            reservasi = res.get(i);
            model.addRow(new Object[]{reservasi.getId(), reservasi.getAccountUsername(), reservasi.getTanggalPesanan(), reservasi.getJumlahMeja(), reservasi.getJumlahOrang()});
        }
    }//GEN-LAST:event_btnArrivedActionPerformed

    private void btnDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecActionPerformed
        service = new com.ubaya.disprog.EzBookingWebService_Service();
        port = service.getEzBookingWebServicePort();

        int row = tableReservation.getSelectedRow();
        int idReservation = (int) tableReservation.getValueAt(row, 0);

        boolean result = true;
        result = port.updateStatusReservasi("Decline", idReservation);
        JOptionPane.showMessageDialog(null, "Success Decline this reservation");
        btnDec.setEnabled(false);
        btnAcpt.setEnabled(false);
        btnArrived.setEnabled(false);

        String usernameRestaurant = FormLogIn.txtUsername.getText();
        int idResto = idRestaurant(usernameRestaurant);
        res = new ArrayList<>();
        res = port.showReservasi(idResto);
        DefaultTableModel model = (DefaultTableModel) tableReservation.getModel();
        model.setRowCount(0);
        for (int i = 0; i < res.size(); i++) {
            reservasi = res.get(i);
            model.addRow(new Object[]{reservasi.getId(), reservasi.getAccountUsername(), reservasi.getTanggalPesanan(), reservasi.getJumlahMeja(), reservasi.getJumlahOrang()});
        }
    }//GEN-LAST:event_btnDecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormShowReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormShowReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormShowReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormShowReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormShowReservasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcpt;
    private javax.swing.JButton btnArrived;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReview;
    private javax.swing.JTable tableReservation;
    // End of variables declaration//GEN-END:variables
}
