/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FormRestaurant;

import FormRegistrasiAccount.FormLogIn;
import com.ubaya.disprog.Reservasi;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class FormHomeRestaurant extends javax.swing.JFrame {

    com.ubaya.disprog.RestaurantWebService_Service service;
    com.ubaya.disprog.RestaurantWebService port;

    /**
     * Creates new form HomeAdminForm
     */
    public FormHomeRestaurant() {
        initComponents();

        service = new com.ubaya.disprog.RestaurantWebService_Service();
        port = service.getRestaurantWebServicePort();
        String usernameRestaurant = FormLogIn.txtUsername.getText();
        int idResto = idRestaurant(usernameRestaurant);

        List<Reservasi> reservasi = new ArrayList<>();
        reservasi = port.showReservasiOnProcess(idResto);
        
        String jumlah = String.valueOf(reservasi.size());
        JOptionPane.showMessageDialog(this, "You have " + jumlah + " reservation On Process");
    }

    public int idRestaurant(String username) {
        service = new com.ubaya.disprog.RestaurantWebService_Service();
        port = service.getRestaurantWebServicePort();
        return port.getIdRestaurant(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnStatisticRestaurant = new javax.swing.JButton();
        btnShowReview = new javax.swing.JButton();
        btnEditRestaurant = new javax.swing.JButton();
        btnShowReservation = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblLogOut = new java.awt.Label();
        btnEditMenu = new javax.swing.JButton();
        btnInputMenu = new javax.swing.JButton();
        btnShowMenu = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Restaurant");
        setBackground(new java.awt.Color(255, 195, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnStatisticRestaurant.setBackground(new java.awt.Color(255, 195, 0));
        btnStatisticRestaurant.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnStatisticRestaurant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormRestaurant/bar-chart (1).png"))); // NOI18N
        btnStatisticRestaurant.setText("Restaurant Statistic");
        btnStatisticRestaurant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 24, 24), 2));
        btnStatisticRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticRestaurantActionPerformed(evt);
            }
        });

        btnShowReview.setBackground(new java.awt.Color(255, 195, 0));
        btnShowReview.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnShowReview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormRestaurant/feedback (1).png"))); // NOI18N
        btnShowReview.setText("Show Review");
        btnShowReview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 24, 24), 2));
        btnShowReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowReviewActionPerformed(evt);
            }
        });

        btnEditRestaurant.setBackground(new java.awt.Color(255, 195, 0));
        btnEditRestaurant.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnEditRestaurant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormRestaurant/editing (1).png"))); // NOI18N
        btnEditRestaurant.setText("Edit Restaurant");
        btnEditRestaurant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 24, 24), 2));
        btnEditRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRestaurantActionPerformed(evt);
            }
        });

        btnShowReservation.setBackground(new java.awt.Color(255, 195, 0));
        btnShowReservation.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnShowReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormRestaurant/eye (1).png"))); // NOI18N
        btnShowReservation.setText("Show Reservation");
        btnShowReservation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 24, 24), 2));
        btnShowReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowReservationActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 195, 0));
        jLabel2.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EZBOOKING");

        lblLogOut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLogOut.setForeground(new java.awt.Color(255, 0, 0));
        lblLogOut.setText("Log Out");
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
        });

        btnEditMenu.setBackground(new java.awt.Color(255, 195, 0));
        btnEditMenu.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnEditMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormRestaurant/writing.png"))); // NOI18N
        btnEditMenu.setText("Edit Menu");
        btnEditMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 24, 24), 2));
        btnEditMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMenuActionPerformed(evt);
            }
        });

        btnInputMenu.setBackground(new java.awt.Color(255, 195, 0));
        btnInputMenu.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnInputMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormRestaurant/menu.png"))); // NOI18N
        btnInputMenu.setText("Input Menu");
        btnInputMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 24, 24), 2));
        btnInputMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputMenuActionPerformed(evt);
            }
        });

        btnShowMenu.setBackground(new java.awt.Color(255, 195, 0));
        btnShowMenu.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnShowMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormRestaurant/pieces-of-cutlery.png"))); // NOI18N
        btnShowMenu.setText("Show Menu");
        btnShowMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 24, 24), 2));
        btnShowMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(btnShowMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnInputMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnShowReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnShowReview, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(btnStatisticRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowReview, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatisticRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInputMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowReviewActionPerformed
        FormShowReview formShowReview = new FormShowReview();
        formShowReview.setVisible(true);
    }//GEN-LAST:event_btnShowReviewActionPerformed

    private void btnEditRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRestaurantActionPerformed
        FormEditDataRestaurant formEditDataRestaurant = new FormEditDataRestaurant();
        formEditDataRestaurant.setVisible(true);
    }//GEN-LAST:event_btnEditRestaurantActionPerformed

    private void btnStatisticRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticRestaurantActionPerformed
        FormStatisticRestaurant formStatisticRestaurant = new FormStatisticRestaurant();
        formStatisticRestaurant.setVisible(true);
    }//GEN-LAST:event_btnStatisticRestaurantActionPerformed

    private void btnShowReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowReservationActionPerformed
        FormShowReservasi formShowReservasi = new FormShowReservasi();
        formShowReservasi.setVisible(true);
    }//GEN-LAST:event_btnShowReservationActionPerformed

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        this.setVisible(false);
        FormLogIn formLogin = new FormLogIn();
        formLogin.setVisible(true);
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void btnEditMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMenuActionPerformed
        FormEditMenu frm = new FormEditMenu();
        frm.setVisible(true);
    }//GEN-LAST:event_btnEditMenuActionPerformed

    private void btnInputMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputMenuActionPerformed
        FormInputMenu frm = new FormInputMenu();
        frm.setVisible(true);
    }//GEN-LAST:event_btnInputMenuActionPerformed

    private void btnShowMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FormShowMenu().setVisible(true);
    }//GEN-LAST:event_btnShowMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHomeRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHomeRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHomeRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHomeRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHomeRestaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditMenu;
    private javax.swing.JButton btnEditRestaurant;
    private javax.swing.JButton btnInputMenu;
    private javax.swing.JButton btnShowMenu;
    private javax.swing.JButton btnShowReservation;
    private javax.swing.JButton btnShowReview;
    private javax.swing.JButton btnStatisticRestaurant;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label lblLogOut;
    // End of variables declaration//GEN-END:variables
}
