/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FormAdmin;

import FormRegistrasiAccount.FormLogIn;
import com.ubaya.disprog.Report;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author RUTH
 */
public class FormCreateReport extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    com.ubaya.disprog.EzBookingWebService_Service service;
    com.ubaya.disprog.EzBookingWebService port;

    public FormCreateReport() {
        initComponents();

        service = new com.ubaya.disprog.EzBookingWebService_Service();
        port = service.getEzBookingWebServicePort();

        String idRest[];
        List<String> idResto = new ArrayList<String>();
        idResto = port.showListIdRestaurant();
        for (String id : idResto) {
            cboRestId.addItem(id);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReport = new javax.swing.JLabel();
        txtQuality = new javax.swing.JTextField();
        lblQuality = new javax.swing.JLabel();
        lblFood = new javax.swing.JLabel();
        txtFood = new javax.swing.JTextField();
        lblReview = new javax.swing.JLabel();
        txtReview = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        cboRestId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 236, 236));

        lblReport.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        lblReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport.setText("REPORT");
        lblReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtQuality.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtQuality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 195, 0)));

        lblQuality.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblQuality.setText("Quality of Service:");

        lblFood.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblFood.setText("Food Quality:");

        txtFood.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtFood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 195, 0)));

        lblReview.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblReview.setText("Review:");

        txtReview.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtReview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 195, 0)));

        btnConfirm.setBackground(new java.awt.Color(255, 195, 0));
        btnConfirm.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnConfirm.setText("CONFIRM");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboRestId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                            .addComponent(txtQuality)
                            .addComponent(txtReview)
                            .addComponent(txtFood)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuality)
                                    .addComponent(lblFood)
                                    .addComponent(lblReview))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblReport, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboRestId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuality)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuality, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblFood)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFood, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblReview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReview, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnConfirm)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        Double qualityService = Double.parseDouble(txtQuality.getText());
        Double foodQuality = Double.parseDouble(txtFood.getText());
        String review = txtReview.getText();
        int idRestaurant = cboRestId.getSelectedIndex();
        String usernameAccount = FormLogIn.txtUsername.getText();

        service = new com.ubaya.disprog.EzBookingWebService_Service();
        port = service.getEzBookingWebServicePort();
        boolean resultSave = port.saveReport(usernameAccount, idRestaurant, qualityService, foodQuality, review);
        if (resultSave == true) {
            JOptionPane.showMessageDialog(this, "Successful!");
        } else {
            JOptionPane.showMessageDialog(this, "Failed!");
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCreateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCreateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCreateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCreateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCreateReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cboRestId;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblQuality;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblReview;
    private javax.swing.JTextField txtFood;
    private javax.swing.JTextField txtQuality;
    private javax.swing.JTextField txtReview;
    // End of variables declaration//GEN-END:variables

//    private static java.util.List<java.lang.String> showListIdRestaurant() {
//        com.ubaya.disprog.EzBookingWebService_Service service = new com.ubaya.disprog.EzBookingWebService_Service();
//        com.ubaya.disprog.EzBookingWebService port = service.getEzBookingWebServicePort();
//        //return port.showListIdRestaurant();
//    }
}
