/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FormAdmin;

import FormRegistrasiAccount.FormLogIn;
import com.ubaya.disprog.Report;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author RUTH
 */
public class FormCreateReport extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    com.ubaya.disprog.AdminWebService_Service service;
    com.ubaya.disprog.AdminWebService port;

    public FormCreateReport() {
        initComponents();

        service = new com.ubaya.disprog.AdminWebService_Service();
        port = service.getAdminWebServicePort();

        List<String> idAllResto = new ArrayList<String>();
        idAllResto = port.showListAllIdRestaurant();
        
        for(String id : idAllResto){
            cboRestId.addItem(id);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReport = new javax.swing.JLabel();
        lblQuality = new javax.swing.JLabel();
        lblFood = new javax.swing.JLabel();
        lblReview = new javax.swing.JLabel();
        txtReview = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        cboRestId = new javax.swing.JComboBox<>();
        spinQualityOfService = new javax.swing.JSpinner();
        spinFoodQuality = new javax.swing.JSpinner();
        lblQuality1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 236, 236));

        lblReport.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        lblReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport.setText("REPORT");
        lblReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblQuality.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblQuality.setText("Quality of Service:");

        lblFood.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblFood.setText("Food Quality:");

        lblReview.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblReview.setText("Review:");

        txtReview.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtReview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 195, 0)));

        btnConfirm.setBackground(new java.awt.Color(255, 195, 0));
        btnConfirm.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnConfirm.setText("CONFIRM");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        lblQuality1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblQuality1.setText("Restaurant Id");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtReview)
                            .addComponent(lblReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReview)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuality1)
                            .addComponent(cboRestId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuality)
                            .addComponent(spinQualityOfService, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFood)
                            .addComponent(spinFoodQuality, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 266, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReport, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuality1)
                        .addGap(9, 9, 9)
                        .addComponent(cboRestId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuality)
                            .addComponent(lblFood))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinQualityOfService)
                            .addComponent(spinFoodQuality))))
                .addGap(22, 22, 22)
                .addComponent(lblReview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReview, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirm)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        Double qualityService = Double.parseDouble(spinQualityOfService.getValue().toString());
        Double foodQuality = Double.parseDouble(spinFoodQuality.getValue().toString());
        String review = txtReview.getText();
        int idRestaurant = Integer.valueOf((String)cboRestId.getSelectedItem());
        String usernameAccount = FormLogIn.txtUsername.getText();

        if (qualityService > 5.0 || foodQuality > 5.0) {
            JOptionPane.showMessageDialog(this, "Quality of service atau food quality tidak boleh lebih dari 5");
        } else {
            service = new com.ubaya.disprog.AdminWebService_Service();
            port = service.getAdminWebServicePort();
            boolean resultSave = port.saveReport(usernameAccount, idRestaurant, qualityService, foodQuality, review);
            if (resultSave == true) {
                JOptionPane.showMessageDialog(this, "Successful!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed!");
            }
        }

    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        FormHomeAdmin frm = new FormHomeAdmin();
        frm.setEnabled(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCreateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCreateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCreateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCreateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCreateReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cboRestId;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblQuality;
    private javax.swing.JLabel lblQuality1;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblReview;
    private javax.swing.JSpinner spinFoodQuality;
    private javax.swing.JSpinner spinQualityOfService;
    private javax.swing.JTextField txtReview;
    // End of variables declaration//GEN-END:variables

//    private static java.util.List<java.lang.String> showListIdRestaurant() {
//        com.ubaya.disprog.EzBookingWebService_Service service = new com.ubaya.disprog.EzBookingWebService_Service();
//        com.ubaya.disprog.EzBookingWebService port = service.getEzBookingWebServicePort();
//        //return port.showListIdRestaurant();
//    }
}
