/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FormAdmin;

import FormRegistrasiAccount.FormLogIn;
import com.ubaya.disprog.Restaurant;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class FormHomeAdmin extends javax.swing.JFrame {

    public String usernameAccount;
    com.ubaya.disprog.AdminWebService_Service service;
    com.ubaya.disprog.AdminWebService port;
    /**
     * Creates new form homeAdminForm
     */
    public FormHomeAdmin() {
        initComponents();
        List<Restaurant> restoArray = new ArrayList<>();
        service = new com.ubaya.disprog.AdminWebService_Service();
        port = service.getAdminWebServicePort();
        restoArray = port.showRestaurantWithFilterForAdmin("All", "", "");

        DefaultTableModel model = (DefaultTableModel) tableRestaurant.getModel();
        for (int i = 0; i < restoArray.size(); i++) {
            Restaurant restaurant = restoArray.get(i);
            model.addRow(new Object[]{restaurant.getNamaRestaurant(), restaurant.getAlamatRestaurant(), restaurant.getMaxTable(), restaurant.getTotalPelanggan(), restaurant.getTotalBintang()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        btnCreateReport = new javax.swing.JButton();
        btnReportHistory = new javax.swing.JButton();
        cboFilter = new javax.swing.JComboBox<>();
        valueFilter = new javax.swing.JTextField();
        btnAsc = new javax.swing.JButton();
        btnDesc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRestaurant = new javax.swing.JTable();
        lblLogOut = new java.awt.Label();
        btnEditReport = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(255, 195, 0));
        jLabel2.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EZBOOKING");

        btnCreateReport.setBackground(new java.awt.Color(255, 195, 0));
        btnCreateReport.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnCreateReport.setIcon(new javax.swing.ImageIcon("C:\\Users\\IVAN\\OneDrive\\Documents\\GitHub\\Project-Disprog\\EzBookingClient\\src\\FormAdmin\\report (1).png")); // NOI18N
        btnCreateReport.setText("Create Report");
        btnCreateReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 24, 24), 2));
        btnCreateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateReportActionPerformed(evt);
            }
        });

        btnReportHistory.setBackground(new java.awt.Color(255, 195, 0));
        btnReportHistory.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnReportHistory.setIcon(new javax.swing.ImageIcon("C:\\Users\\IVAN\\OneDrive\\Documents\\GitHub\\Project-Disprog\\EzBookingClient\\src\\FormAdmin\\history (1).png")); // NOI18N
        btnReportHistory.setText("Report History");
        btnReportHistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 24, 24), 2));
        btnReportHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportHistoryActionPerformed(evt);
            }
        });

        cboFilter.setBackground(new java.awt.Color(255, 195, 0));
        cboFilter.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        cboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Restaurant", "Alamat", "Number of Table", "Total Customers", "Rating" }));
        cboFilter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 24, 24)));

        valueFilter.setBackground(new java.awt.Color(255, 195, 0));
        valueFilter.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N

        btnAsc.setBackground(new java.awt.Color(255, 195, 0));
        btnAsc.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnAsc.setText("Ascending");
        btnAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAscActionPerformed(evt);
            }
        });

        btnDesc.setBackground(new java.awt.Color(255, 195, 0));
        btnDesc.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnDesc.setText("Descending");
        btnDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescActionPerformed(evt);
            }
        });

        tableRestaurant.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        tableRestaurant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant", "Alamat", "Number of Table", "Total Customers", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRestaurant.setName(""); // NOI18N
        jScrollPane2.setViewportView(tableRestaurant);
        if (tableRestaurant.getColumnModel().getColumnCount() > 0) {
            tableRestaurant.getColumnModel().getColumn(0).setResizable(false);
            tableRestaurant.getColumnModel().getColumn(1).setResizable(false);
            tableRestaurant.getColumnModel().getColumn(2).setResizable(false);
            tableRestaurant.getColumnModel().getColumn(3).setResizable(false);
            tableRestaurant.getColumnModel().getColumn(4).setResizable(false);
        }

        lblLogOut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLogOut.setForeground(new java.awt.Color(255, 0, 0));
        lblLogOut.setText("Log Out");
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
        });

        btnEditReport.setBackground(new java.awt.Color(255, 195, 0));
        btnEditReport.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnEditReport.setIcon(new javax.swing.ImageIcon("C:\\Users\\IVAN\\OneDrive\\Documents\\GitHub\\Project-Disprog\\EzBookingClient\\src\\FormRestaurant\\editing (1).png")); // NOI18N
        btnEditReport.setText("Edit Report");
        btnEditReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 24, 24), 2));
        btnEditReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboFilter, 0, 258, Short.MAX_VALUE)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addComponent(btnAsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(176, 176, 176))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnCreateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditReport, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(btnReportHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsc)
                    .addComponent(btnDesc))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditReport, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateReportActionPerformed
        FormCreateReport formCreateReport = new FormCreateReport();
        formCreateReport.setVisible(true);
    }//GEN-LAST:event_btnCreateReportActionPerformed

    private void btnReportHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportHistoryActionPerformed
        FormShowReportHistory formShowReportHistory = new FormShowReportHistory();
        formShowReportHistory.setVisible(true);

    }//GEN-LAST:event_btnReportHistoryActionPerformed

    private void btnAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAscActionPerformed
        List<Restaurant> restoArray = new ArrayList<>();

        service = new com.ubaya.disprog.AdminWebService_Service();
        port = service.getAdminWebServicePort();
        String filter = "";
        String cboSel = cboFilter.getSelectedItem().toString();
        if (cboSel.equals("Nama Restaurant")) {
            filter = "nama";
        } else if (cboSel.equals("Alamat")) {
            filter = "alamat";
        } else if (cboSel.equals("Number of Table")) {
            filter = "max_table";
        } else if (cboSel.equals("Total Customers")) {
            filter = "total_pelanggaan";
        } else if (cboSel.equals("All")) {
            filter = "All";
        } else {
            filter = "overall_rating";
        }
        restoArray = port.showRestaurantWithFilterForAdmin(filter, valueFilter.getText(), "asc");

        DefaultTableModel model = (DefaultTableModel) tableRestaurant.getModel();
        model.setRowCount(0);
        for (int i = 0; i < restoArray.size(); i++) {
            Restaurant restaurant = restoArray.get(i);
            model.addRow(new Object[]{restaurant.getNamaRestaurant(), restaurant.getAlamatRestaurant(), restaurant.getMaxTable(), restaurant.getTotalPelanggan(), restaurant.getTotalBintang()});
        }
    }//GEN-LAST:event_btnAscActionPerformed

    private void btnDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescActionPerformed
        List<Restaurant> restoArray = new ArrayList<>();
        service = new com.ubaya.disprog.AdminWebService_Service();
        port = service.getAdminWebServicePort();
        String filter = "";
        String cboSel = cboFilter.getSelectedItem().toString();
        if (cboSel.equals("Nama Restaurant")) {
            filter = "nama";
        } else if (cboSel.equals("Alamat")) {
            filter = "alamat";
        } else if (cboSel.equals("Number of Table")) {
            filter = "max_table";
        } else if (cboSel.equals("Total Customers")) {
            filter = "total_pelanggaan";
        } else if (cboSel.equals("All")) {
            filter = "All";
        } else {
            filter = "overall_rating";
        }
        restoArray = port.showRestaurantWithFilterForAdmin(filter, valueFilter.getText(), "desc");

        DefaultTableModel model = (DefaultTableModel) tableRestaurant.getModel();
        model.setRowCount(0);
        for (int i = 0; i < restoArray.size(); i++) {
            Restaurant restaurant = restoArray.get(i);
            model.addRow(new Object[]{restaurant.getNamaRestaurant(), restaurant.getAlamatRestaurant(), restaurant.getMaxTable(), restaurant.getTotalPelanggan(), restaurant.getTotalBintang()});
        }
    }//GEN-LAST:event_btnDescActionPerformed

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        this.setVisible(false);
        FormLogIn formLogin = new FormLogIn();
        formLogin.setVisible(true);
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void btnEditReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditReportActionPerformed
        FormEditReport formEditReport = new FormEditReport();
        formEditReport.setVisible(true);
    }//GEN-LAST:event_btnEditReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHomeAdmin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsc;
    private javax.swing.JButton btnCreateReport;
    private javax.swing.JButton btnDesc;
    private javax.swing.JButton btnEditReport;
    private javax.swing.JButton btnReportHistory;
    private javax.swing.JComboBox<String> cboFilter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.Label lblLogOut;
    private javax.swing.JTable tableRestaurant;
    private javax.swing.JTextField valueFilter;
    // End of variables declaration//GEN-END:variables
}
